### ISSUE TITLE
Fix container scenarios to accept just the signal number for the action

### ISSUE THREAD

**Issue by chaitanyaenr** [krkn-chaos/krkn#350]
The current container scenario allows users to pass an action with a command that gets run inside a container, this allows users to potentially run any command vs just passing the kill signal which is the intent. The config should look something like:
 
```
scenarios:
- name: "kill etcd container"
  namespace: "openshift-etcd"
  label_selector: "k8s-app=etcd"
  container_name: "etcd"
  action: "1" ( instead of kill 1 )
  count: 1
  retry_wait: 60
```
