### ISSUE TITLE
Cannot run Kraken Dockerized version

### ISSUE THREAD

**Issue by pravalikaponugupati** [krkn-chaos/krkn#460]
I am trying to run  kraken  dockerized version, however there seems to be lot of uncertainty around `kubeconfig` and `config.yaml` files.
I am trying to test this on local. I have both kubectl and minikube installed on my system. I had been referring to this documentation: https://github.com/redhat-chaos/krkn/blob/main/docs/installation.md

I have a docker compose file that looks something like this:
```yaml

version: "3.7"    
services:
  app:
    image: quay.io/redhat-chaos/krkn:latest  
    volumes:
      - type: bind
        source: C:/Users/voldemort/.kube/config
        target: /root/.kube/config:Z

      - type: bind
        source: C:/Users/voldemort/Desktop/ARM/config/config.yaml
        target: /root/kraken/config/config.yaml:Z

```
I see that the kube-config is well present in the path  `C:/Users/voldemort/.kube/config`.
When I do docker compose up I seem to be experiencing the following error : 

![image](https://github.com/redhat-chaos/krkn/assets/103594167/dc96495b-f8e5-435d-9a0d-6afcc706c5f0)

Any idea what might be wrong. Appreciate the help.
