### ISSUE TITLE
Support checking application availability during and post chaos

### ISSUE THREAD

**Issue by chaitanyaenr** [krkn-chaos/krkn#755]
Krkn currently has various checks to make sure the targeted component recovered from chaos and can validate SLOs via prometheus during chaos. Users can benefit from having a way to define url's accessible via http or https as part of the krkn config, check the availability both during/post chaos and report the status as part of the summary json.

For instance, we can add the following to the config ( https://github.com/krkn-chaos/krkn/blob/main/config/config.yaml ):

```
health_checks:
    urls: [http://www.app.example.com, https://www.app2.example.com]
    auth: 
    bearer_token:  
```

The status of the url's can then be published as part of the summary/telemetry json:

```
"health_checks": [
      {
           "url": "http://www.app.example.com",
            status: "True",
            status_code: "200"
      },
      {
           "url" "https://www.app2.example.com",
            status: "False",
            status_code: "503"
      }
]
    
```
