### ISSUE TITLE
Be able to save metrics locally

### ISSUE THREAD

**Issue by paigerube14** [krkn-chaos/krkn#829]
Currently, if a user set enable_metrics to True but does not set enable_elastic to True (False), the metrics are collected and nothing is done with them. If the following set up occurs, I think we should save the metrics to a file at a tmp location (maybe based on the run_uuid to be specific to a run) 

```
performance_monitoring:
....                                  
    enable_alerts: False                                  # Runs the queries specified in the alert profile and displays the info or exits 1 when severity=error
    enable_metrics: True
    alert_profile: config/alerts.yaml                          # Path or URL to alert profile with the prometheus queries
    metrics_profile: config/metrics-report.yaml
    check_critical_alerts: False                          # When enabled will check prometheus for critical alerts firing post chaos
elastic:
    enable_elastic: False
    verify_certs: False
    elastic_url: ""                                         # To track results in elasticsearch, give url to server here; will post telemetry details when url and index not blank
    elastic_port: 32766
    username: "elastic"
    password: "test"
    metrics_index: "krkn-metrics"
    alerts_index: "krkn-alerts"
    telemetry_index: "krkn-telemetry"
```

Code block associated with issue

https://github.com/krkn-chaos/krkn/blob/0dcb901da11c7b3760e6fe0ab2288b222745ac57/krkn/prometheus/client.py#L253-L259
